# Generated by Django 4.2.25 on 2025-10-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('site', 'protocol', 'ip_address', 'port')},
        ),
    ]
