# Generated by Django 4.2.25 on 2025-10-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_device_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
