# Generated by Django 4.2.25 on 2025-10-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_importjob_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('validated', '已校验'), ('failed', '失败'), ('applied', '已生效')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='status',
            field=models.CharField(choices=[('pending', '待启动'), ('running', '运行中'), ('succeeded', '成功'), ('failed', '失败'), ('stopped', '已停止')], default='pending', max_length=16),
        ),
    ]
