# Generated by Django 4.2.25 on 2026-04-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_importjob_status_alter_taskrun_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='to_kafka',
        ),
    ]
