# Generated by Django 4.2.25 on 2026-04-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_remove_point_to_kafka'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
