# Generated by Django 4.2.25 on 2026-04-29 08:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_alter_device_unique_together_alter_device_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acqtask',
            name='sample_rate_hz',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='采集频率(Hz)。修改后将自动重启运行中的会话。', max_digits=8),
        ),
    ]
