# Generated by Django 4.2.25 on 2026-04-30 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_acqtask_sample_rate_hz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acqtask',
            name='schedule',
        ),
    ]
