# Generated by Django 4.2.25 on 2026-05-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_remove_acqtask_schedule'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='point',
            index=models.Index(fields=['code'], name='point_code_idx'),
        ),
    ]
