# Generated by Django 4.2.25 on 2026-05-21 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('configuration', '0009_point_point_code_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='acqtask',
            name='edge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='fleet.edgenode'),
        ),
    ]
