# Generated by Django 4.2.25 on 2026-07-17 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_point_point_code_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScadaGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('source_ip', models.CharField(blank=True, default='', max_length=255)),
                ('source_port', models.PositiveIntegerField(default=8883)),
                ('mqtt_use_tls', models.BooleanField(default=True)),
                ('mqtt_username', models.CharField(blank=True, default='', max_length=128)),
                ('mqtt_password', models.CharField(blank=True, default='', max_length=255)),
                ('mqtt_qos', models.PositiveSmallIntegerField(default=0)),
                ('mqtt_client_id', models.CharField(blank=True, default='', max_length=128)),
                ('mqtt_read_timeout', models.FloatField(default=5.0)),
                ('product_key', models.CharField(blank=True, default='', max_length=128)),
                ('topic_template', models.CharField(default='/sys/{product_key}/device/{device_name}/thing/property/{code}/post', max_length=255)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='configuration.scadagateway'),
        ),
    ]
