# Generated by Django 4.2.25 on 2026-05-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('token_hash', models.CharField(db_index=True, max_length=128)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('online', 'online'), ('offline', 'offline')], default='pending', max_length=16)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
