# Generated by Django 4.2.25 on 2026-05-21 22:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_acqtask_edge'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('last_reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='fleet.edgenode')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_statuses', to='configuration.acqtask')),
            ],
            options={
                'ordering': ('edge', 'task'),
                'indexes': [models.Index(fields=['task', '-last_reported_at'], name='edge_task_status_idx')],
                'unique_together': {('edge', 'task')},
            },
        ),
        migrations.CreateModel(
            name='EdgeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_state', models.CharField(choices=[('running', 'running'), ('stopped', 'stopped')], default='running', max_length=16)),
                ('config_version', models.PositiveIntegerField(default=0)),
                ('last_applied_version', models.PositiveIntegerField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fleet.edgenode')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_assignments', to='configuration.acqtask')),
            ],
            options={
                'ordering': ('edge', 'task'),
                'unique_together': {('edge', 'task')},
            },
        ),
    ]
