# Generated by Django 4.2.25 on 2026-04-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0005_remove_point_to_kafka'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', '运行中'), ('paused', '已暂停'), ('stopped', '已停止'), ('error', '错误')], default='running', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery任务ID', max_length=255)),
                ('pid', models.IntegerField(blank=True, help_text='进程ID', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='configuration.acqtask')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='configuration.workerendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_code', models.CharField(help_text='测点编码', max_length=128)),
                ('timestamp', models.DateTimeField(help_text='采集时间戳')),
                ('value', models.JSONField(help_text='采集值(支持各种类型)')),
                ('quality', models.CharField(default='good', help_text='数据质量: good/bad/uncertain', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='acquisition.acquisitionsession')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session', '-timestamp'], name='acquisition_session_4e83d3_idx'), models.Index(fields=['point_code', '-timestamp'], name='acquisition_point_c_8cc0f1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='acquisitionsession',
            index=models.Index(fields=['status', '-created_at'], name='acquisition_status_4a52b8_idx'),
        ),
        migrations.AddIndex(
            model_name='acquisitionsession',
            index=models.Index(fields=['celery_task_id'], name='acquisition_celery__a58b2d_idx'),
        ),
    ]
