# Generated by Django 4.2.25 on 2026-04-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('point_code', models.CharField(db_index=True, help_text='匹配读数中的 code 字段', max_length=128)),
                ('device_code', models.CharField(blank=True, help_text='若指定,仅匹配此设备的同名测点', max_length=255)),
                ('operator', models.CharField(choices=[('gt', '> 大于'), ('ge', '≥ 大于等于'), ('lt', '< 小于'), ('le', '≤ 小于等于'), ('eq', '= 等于'), ('ne', '≠ 不等于'), ('between', '区间内'), ('outside', '区间外')], default='gt', max_length=16)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('threshold_high', models.FloatField(blank=True, help_text='between/outside 操作符使用', null=True)),
                ('severity', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('critical', '严重')], default='warning', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_code', models.CharField(max_length=128)),
                ('device_code', models.CharField(blank=True, max_length=255)),
                ('value', models.JSONField()),
                ('status', models.CharField(choices=[('firing', '未确认'), ('acked', '已确认'), ('cleared', '已恢复')], default='firing', max_length=16)),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=64)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='acquisition.alarmrule')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='acquisition.acquisitionsession')),
            ],
            options={
                'ordering': ['-fired_at'],
                'indexes': [models.Index(fields=['status', '-fired_at'], name='acquisition_status_89f957_idx'), models.Index(fields=['point_code', '-fired_at'], name='acquisition_point_c_ea2358_idx')],
            },
        ),
    ]
