# Generated by Django 4.2.25 on 2026-05-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0002_alarmrule_alarm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['point_code', 'status'], name='alarm_point_status_idx'),
        ),
    ]
