# Generated by Django 4.2.25 on 2026-07-13 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0003_alarm_alarm_point_status_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='category',
            field=models.CharField(choices=[('threshold', '阈值'), ('connectivity', '连接'), ('system', '系统'), ('lifecycle', '生命周期')], db_index=True, default='threshold', max_length=16),
        ),
        migrations.AddField(
            model_name='alarm',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alarm',
            name='severity',
            field=models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('critical', '严重')], default='warning', max_length=16),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='acquisition.alarmrule'),
        ),
    ]
