# Generated by Django 4.2.25 on 2026-05-22 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_m3_uplink'),
        ('acquisition', '0003_alarm_alarm_point_status_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='edge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='fleet.edgenode'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['edge', '-fired_at'], name='alarm_edge_fired_idx'),
        ),
    ]
